<?php

return array(

	'namespaces' => array(

		'allOf'         => 'Respect\\Validation\\Rules\\',
		'alnum'         => 'Respect\\Validation\\Rules\\',
		'alpha'         => 'Respect\\Validation\\Rules\\',
		'alwaysInvalid' => 'Respect\\Validation\\Rules\\',
		'alwaysValid'   => 'Respect\\Validation\\Rules\\',
		'arr'           => 'Respect\\Validation\\Rules\\',
		'attribute'     => 'Respect\\Validation\\Rules\\',
		'base'          => 'Respect\\Validation\\Rules\\',
		'between'       => 'Respect\\Validation\\Rules\\',
		'bool'          => 'Respect\\Validation\\Rules\\',
		'call'          => 'Respect\\Validation\\Rules\\',
		'callback'      => 'Respect\\Validation\\Rules\\',
		'charset'       => 'Respect\\Validation\\Rules\\',
		'cnh'           => 'Respect\\Validation\\Rules\\',
		'cnpj'          => 'Respect\\Validation\\Rules\\',
		'consonant'     => 'Respect\\Validation\\Rules\\',
		'contains'      => 'Respect\\Validation\\Rules\\',
		'countryCode'   => 'Respect\\Validation\\Rules\\',
		'cpf'           => 'Respect\\Validation\\Rules\\',
		'creditCard'    => 'Respect\\Validation\\Rules\\',
		'date'          => 'Respect\\Validation\\Rules\\',
		'digit'         => 'Respect\\Validation\\Rules\\',
		'directory'     => 'Respect\\Validation\\Rules\\',
		'domain'        => 'Respect\\Validation\\Rules\\',
		'each'          => 'Respect\\Validation\\Rules\\',
		'email'         => 'Respect\\Validation\\Rules\\',
		'endsWith'      => 'Respect\\Validation\\Rules\\',
		'equals'        => 'Respect\\Validation\\Rules\\',
		'even'          => 'Respect\\Validation\\Rules\\',
		'exists'        => 'Respect\\Validation\\Rules\\',
		'file'          => 'Respect\\Validation\\Rules\\',
		'float'         => 'Respect\\Validation\\Rules\\',
		'graph'         => 'Respect\\Validation\\Rules\\',
		'in'            => 'Respect\\Validation\\Rules\\',
		'instance'      => 'Respect\\Validation\\Rules\\',
		'int'           => 'Respect\\Validation\\Rules\\',
		'ip'            => 'Respect\\Validation\\Rules\\',
		'json'          => 'Respect\\Validation\\Rules\\',
		'key'           => 'Respect\\Validation\\Rules\\',
		'leapDate'      => 'Respect\\Validation\\Rules\\',
		'leapYear'      => 'Respect\\Validation\\Rules\\',
		'length'        => 'Respect\\Validation\\Rules\\',
		'lowercase'     => 'Respect\\Validation\\Rules\\',
		'macAddress'    => 'Respect\\Validation\\Rules\\',
		'max'           => 'Respect\\Validation\\Rules\\',
		'min'           => 'Respect\\Validation\\Rules\\',
		'minimumAge'    => 'Respect\\Validation\\Rules\\',
		'multiple'      => 'Respect\\Validation\\Rules\\',
		'negative'      => 'Respect\\Validation\\Rules\\',
		'noneOf'        => 'Respect\\Validation\\Rules\\',
		'not'           => 'Respect\\Validation\\Rules\\',
		'notEmpty'      => 'Respect\\Validation\\Rules\\',
		'noWhitespace'  => 'Respect\\Validation\\Rules\\',
		'nullValue'     => 'Respect\\Validation\\Rules\\',
		'numeric'       => 'Respect\\Validation\\Rules\\',
		'object'        => 'Respect\\Validation\\Rules\\',
		'odd'           => 'Respect\\Validation\\Rules\\',
		'oneOf'         => 'Respect\\Validation\\Rules\\',
		'perfectSquare' => 'Respect\\Validation\\Rules\\',
		'phone'         => 'Respect\\Validation\\Rules\\',
		'positive'      => 'Respect\\Validation\\Rules\\',
		'primeNumber'   => 'Respect\\Validation\\Rules\\',
		'prnt'          => 'Respect\\Validation\\Rules\\',
		'punct'         => 'Respect\\Validation\\Rules\\',
		'readable'      => 'Respect\\Validation\\Rules\\',
		'regex'         => 'Respect\\Validation\\Rules\\',
		'roman'         => 'Respect\\Validation\\Rules\\',
		'sf'            => 'Respect\\Validation\\Rules\\',
		'slug'          => 'Respect\\Validation\\Rules\\',
		'space'         => 'Respect\\Validation\\Rules\\',
		'startsWith'    => 'Respect\\Validation\\Rules\\',
		'string'        => 'Respect\\Validation\\Rules\\',
		'symbolicLink'  => 'Respect\\Validation\\Rules\\',
		'tld'           => 'Respect\\Validation\\Rules\\',
		'uploaded'      => 'Respect\\Validation\\Rules\\',
		'uppercase'     => 'Respect\\Validation\\Rules\\',
		'version'       => 'Respect\\Validation\\Rules\\',
		'vowel'         => 'Respect\\Validation\\Rules\\',
		'when'          => 'Respect\\Validation\\Rules\\',
		'writable'      => 'Respect\\Validation\\Rules\\',
		'xdigit'        => 'Respect\\Validation\\Rules\\',
		'zend'          => 'Respect\\Validation\\Rules\\',
		
		'abn'           => 'Kitbs\\Datasmart\\Validate\\Rules\\',
		'acn'           => 'Kitbs\\Datasmart\\Validate\\Rules\\',
		
		'ean13'        => 'Kitbs\\Datasmart\\Validate\\Rules\\',
		'isbn'        => 'Kitbs\\Datasmart\\Validate\\Rules\\',
		'vat'        => 'Kitbs\\Datasmart\\Validate\\Rules\\',




		),

);
